In [9]:
import random
from random import randint
import numpy as np

In [3]:

from google.colab import files
uploaded = files.upload()
import pandas as pd
inputdata = pd.read_csv(r'input.csv')

# import pandas as pd
# inputdata = pd.read_csv("input.csv")
# inputdata
# inputdata.iloc[: , :4]

cleandata = inputdata.dropna(thresh=3,axis=1)
cleandata


Saving input.csv to input (1).csv


Teacher Batch Section  Course
0       T1    B1        A     C1
1       T1    B1        B     C1
2       T2    B1        A     C2
3       T2    B1        B     C2
4       T3    B1        A     C3
5       T3    B1        B     C3
6       T4    B1        A     C4
7       T4    B1        B     C4
8       T1    B1        A     C5
9       T2    B1        B     C5
10      T3    B2        A     C6
11      T3    B2        B     C6
12      T6    B2        A     C7
13      T6    B2        B     C7
14      T6    B2        A     C8
15      T7    B2        B     C8
16      T7    B2        A     C9
17      T7    B2        B     C9
18      T8    B2        A    C10
19      T8    B2        B    C10
20      T8    B2        A     C3
21      T6    B3        A    C11
22      T4    B3        B    C11
23      T4    B3        A    C12
24      T5    B3        B    C12
25      T5    B3        A    C13
26      T6    B3        B    C13
27      T5    B3        A    C14
28      T9    B3        B    C14
29      T9    B3        A    C15
30      T9    B3        B    C15
31      T1    B3        A     C1
32      T7    B3        A     C8
33     T10    B1        A     L3
34     T10    B1        B     L3
35     T10    B2        A     L6
36     T11    B2        B     L6
37     T11    B3        A    L12
38     T12    B3        B    L12
39     T12    B2        A     L3

In [5]:
X = cleandata.iloc[:, :].values
# X

In [6]:
y = cleandata.iloc[:, -1].values
# y = cleandata.iloc[:, -1]

In [7]:
from sklearn import preprocessing
l= preprocessing.LabelEncoder()
Processeddata = cleandata.apply(l.fit_transform)
# Processeddata


# another= pd.get_dummies(data=cleandata)
# another

In [10]:
csv_size = len(Processeddata)
# sampl = np.random.randint(8.5,17, size=(csv_size,1))
sampl = 8.5 + (np.random.randint(1,5, size=(csv_size,1))) * np.random.uniform(low=1.5, high=1.5, size=(csv_size,1))
sampl
Processeddata['StartTime'] = sampl
sampl = np.random.randint(1,4, size=(csv_size,1))
Processeddata['Room'] = sampl
sampl = np.random.randint(1,8, size=(csv_size,1))
Processeddata['Day'] = sampl
# Processeddata

In [11]:
population = []
for index, row in Processeddata.iterrows():
#     print(row)
    population.append(row.values)    
population

[array([ 0.,  0.,  0.,  0., 10.,  3.,  1.]),
 array([ 0. ,  0. ,  1. ,  0. , 11.5,  2. ,  5. ]),
 array([ 4. ,  0. ,  0. ,  7. , 11.5,  2. ,  3. ]),
 array([ 4.,  0.,  1.,  7., 13.,  2.,  6.]),
 array([ 5. ,  0. ,  0. ,  8. , 14.5,  1. ,  7. ]),
 array([ 5. ,  0. ,  1. ,  8. , 14.5,  3. ,  1. ]),
 array([ 6. ,  0. ,  0. ,  9. , 14.5,  1. ,  7. ]),
 array([ 6.,  0.,  1.,  9., 10.,  2.,  5.]),
 array([ 0. ,  0. ,  0. , 10. , 14.5,  2. ,  1. ]),
 array([ 4. ,  0. ,  1. , 10. , 14.5,  3. ,  3. ]),
 array([ 5. ,  1. ,  0. , 11. , 14.5,  2. ,  5. ]),
 array([ 5. ,  1. ,  1. , 11. , 11.5,  1. ,  3. ]),
 array([ 8. ,  1. ,  0. , 12. , 14.5,  3. ,  3. ]),
 array([ 8. ,  1. ,  1. , 12. , 14.5,  2. ,  6. ]),
 array([ 8. ,  1. ,  0. , 13. , 11.5,  1. ,  1. ]),
 array([ 9. ,  1. ,  1. , 13. , 14.5,  1. ,  4. ]),
 array([ 9. ,  1. ,  0. , 14. , 11.5,  2. ,  2. ]),
 array([ 9.,  1.,  1., 14., 13.,  2.,  4.]),
 array([10.,  1.,  0.,  1., 10.,  2.,  5.]),
 array([10.,  1.,  1.,  1., 10.,  2.,  2.]),
 a

In [12]:
#function for crossover of two parents
def CrossoverofTwoParent(parent1,parent2):
#     print("P1",parent1)
#     print("P2",parent2)
    crossover_point=random.randint(2,int(len(parent1)/2))
#     print("\n\n\n   Point of Cross :::::    ",pointofcross)
#     for i in range(pointofcross):
#         print(parent1[i],parent2[i])=print(parent2[i],parent1[i])
       
    newcomb1 = []
    for i in range(0, crossover_point):
        newcomb1.append(parent1[i])
    for i in range(crossover_point, len(parent1)):
        newcomb1.append(parent2[i])

    newcomb2 = []
    for i in range(0, crossover_point):
        newcomb2.append(parent2[i])
    for i in range(crossover_point, len(parent1)):
        newcomb2.append(parent1[i])
    
#     print("C1",newcomb1)
#     print("C2",newcomb2)
    newlist=[]
    newlist.append(newcomb1)
    newlist.append(newcomb2)
#     if parent1.all not in population:
#         newlist.append(parent1)
#     if parent1.all not in population:
#         newlist.append(parent2)

    return newlist
#     print("Printing New List  \n\n",newlist,"\n\n")
#function for cross over of a generation
def genCross(population):
    print("Crossing over the generation to create new generation...")
    size=len(population)
#     print(size)
    i=0
    while i in range(0,size):
        newlist=[]
        
        newlist=CrossoverofTwoParent(population[i],population[i+1])
        
        population.extend(newlist)
        i=i+2
genCross(population)

Crossing over the generation to create new generation...


In [13]:
population

[array([ 0.,  0.,  0.,  0., 10.,  3.,  1.]),
 array([ 0. ,  0. ,  1. ,  0. , 11.5,  2. ,  5. ]),
 array([ 4. ,  0. ,  0. ,  7. , 11.5,  2. ,  3. ]),
 array([ 4.,  0.,  1.,  7., 13.,  2.,  6.]),
 array([ 5. ,  0. ,  0. ,  8. , 14.5,  1. ,  7. ]),
 array([ 5. ,  0. ,  1. ,  8. , 14.5,  3. ,  1. ]),
 array([ 6. ,  0. ,  0. ,  9. , 14.5,  1. ,  7. ]),
 array([ 6.,  0.,  1.,  9., 10.,  2.,  5.]),
 array([ 0. ,  0. ,  0. , 10. , 14.5,  2. ,  1. ]),
 array([ 4. ,  0. ,  1. , 10. , 14.5,  3. ,  3. ]),
 array([ 5. ,  1. ,  0. , 11. , 14.5,  2. ,  5. ]),
 array([ 5. ,  1. ,  1. , 11. , 11.5,  1. ,  3. ]),
 array([ 8. ,  1. ,  0. , 12. , 14.5,  3. ,  3. ]),
 array([ 8. ,  1. ,  1. , 12. , 14.5,  2. ,  6. ]),
 array([ 8. ,  1. ,  0. , 13. , 11.5,  1. ,  1. ]),
 array([ 9. ,  1. ,  1. , 13. , 14.5,  1. ,  4. ]),
 array([ 9. ,  1. ,  0. , 14. , 11.5,  2. ,  2. ]),
 array([ 9.,  1.,  1., 14., 13.,  2.,  4.]),
 array([10.,  1.,  0.,  1., 10.,  2.,  5.]),
 array([10.,  1.,  1.,  1., 10.,  2.,  2.]),
 a

In [14]:
def Mutation(population):
#     random.randint(a,b)
    size = len(population[0])
    
    for x in population:
        x[0] = random.randint(0,11)
    return population

Mutation(population)

[array([ 6.,  0.,  0.,  0., 10.,  3.,  1.]),
 array([ 8. ,  0. ,  1. ,  0. , 11.5,  2. ,  5. ]),
 array([ 8. ,  0. ,  0. ,  7. , 11.5,  2. ,  3. ]),
 array([ 0.,  0.,  1.,  7., 13.,  2.,  6.]),
 array([11. ,  0. ,  0. ,  8. , 14.5,  1. ,  7. ]),
 array([10. ,  0. ,  1. ,  8. , 14.5,  3. ,  1. ]),
 array([ 7. ,  0. ,  0. ,  9. , 14.5,  1. ,  7. ]),
 array([ 8.,  0.,  1.,  9., 10.,  2.,  5.]),
 array([10. ,  0. ,  0. , 10. , 14.5,  2. ,  1. ]),
 array([ 0. ,  0. ,  1. , 10. , 14.5,  3. ,  3. ]),
 array([ 9. ,  1. ,  0. , 11. , 14.5,  2. ,  5. ]),
 array([11. ,  1. ,  1. , 11. , 11.5,  1. ,  3. ]),
 array([ 8. ,  1. ,  0. , 12. , 14.5,  3. ,  3. ]),
 array([10. ,  1. ,  1. , 12. , 14.5,  2. ,  6. ]),
 array([ 1. ,  1. ,  0. , 13. , 11.5,  1. ,  1. ]),
 array([ 6. ,  1. ,  1. , 13. , 14.5,  1. ,  4. ]),
 array([ 2. ,  1. ,  0. , 14. , 11.5,  2. ,  2. ]),
 array([ 9.,  1.,  1., 14., 13.,  2.,  4.]),
 array([ 0.,  1.,  0.,  1., 10.,  2.,  5.]),
 array([ 8.,  1.,  1.,  1., 10.,  2.,  2.]),
 a

In [20]:
def NoTeacherSameTime(chromosome):
    # print(chromosome)
    count = 0
    for x in population:
#         if(np.array_equal(x,chromosome)):
        if(chromosome[0] == x[0] and chromosome[4] == x[4]):
#             print("found")
            count+=1
    if count > 1:
#         print("count",count)
        return 0
    else:
        return 1
    
NoTeacherSameTime(population[0])

0

In [21]:
def NoSectionSameTime(chromosome):
    count = 0
    for x in population:
#         if(np.array_equal(x,chromosome)):
        if(chromosome[2] == x[2] and chromosome[4] == x[4]):
#             print("found")
            count+=1
    if count > 1:
        return 0
    else:
        return 1
    
    
def NoClassroomSametime(chromosome):
    count = 0
    for x in population:
#         if(np.array_equal(x,chromosome)):
        if(chromosome[5] == x[5] and chromosome[4] == x[4]):
#             print("found")
            count+=1
    if count > 1:
        return 0
    else:
        return 1
    
    
def consecutive(chromosome):
    count = 0
    for x in population:
#         if(np.array_equal(x,chromosome)):
        if(chromosome[0] == x[0] and chromosome[6] == x[6]):
            if((chromosome[4]  - x[4] == 1.5) or ( x[4] - chromosome[4] == 1.5) or (chromosome[4]  - x[4] == 3.0) or ( x[4] - chromosome[4] == 3.0) ):
                count+=1
       
       
    if count < 3:
        return 1
    else:
        return 0
    
    
def NoClassBeforeAfter(chromosome):
    count = 0
    
    if( (chromosome[4] + 1.5) >= 8.5 and (chromosome[4] + 1.5) <=17) :
        return 1
    else:
        return 0
    
    
def weekend(chromosome):
    if(chromosome[6] == 6 or chromosome[6] == 7):
        return 0
    else:
        return 1
    

In [ ]:
from numpy.ma.core import empty
def Check_Hard_Constraints(population):
    
    HardFitChromosomes = []
    goodones = []
    AllFitScore = [] #Fitness score for all chormosoes
    currScore = 0 # fitness score for current chromosome
    
    while(not len(HardFitChromosomes)):
      for x in population:
          
          if(NoTeacherSameTime(x)):
              currScore += 1
          # print("Current Score",currScore)
          if(NoSectionSameTime(x)):
              currScore += 1
              
          if(NoClassroomSametime(x)):
              currScore += 1
  #         print("Current Score",currScore)
          if(consecutive(x)):
              currScore += 1
              
          if(NoClassBeforeAfter(x)):
              currScore += 1
  #         print("Current Score",currScore)
          if(weekend(x)):
              currScore += 1
  #         print("Current Score",currScore)
          if(currScore >=4):
            goodones.append(x)
          if(currScore == 6):
              HardFitChromosomes.append(x)
              print("Current Score",currScore)
          # else:
              # print("Not passed")
              
          
          currScore = 0
      population.extend(goodones)
      genCross(population)
      Mutation(population)
    return HardFitChromosomes

Check_Hard_Constraints(population)

Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...
Crossing over the generation to create new generation...


In [ ]:

def Givebestsolution(population):
    HardFitChromosomes = []
    HardFitChromosomes = Check_Hard_Constraints(population)
    
    return HardFitChromosomes

FitChromosomes = Givebestsolution(population)
print(len(FitChromosomes))
print("\n\n Best Chromosomes : \n\n", )
            

In [ ]:
print("Khush Rhain , Khush Rakhian, Jzak Allah")